version: '3.7'

services: 
    webapp-server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: admin-cakrawala
        ports: 
            - "3000:3000"